---
# task for hadenlabs.xvfb

- include: install.d/CentOS.yaml
  when: ansible_distribution == "CentOS"
  tags:
    - xvfb

- include: install.d/Ubuntu.yaml
  when: ansible_distribution == "Ubuntu"
  tags:
    - xvfb