---

# task file for dgnest.xvfb

- name: Ensure apt cache is up to date
  apt:
    update_cache: yes


- name: Install xvfb dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items: _xvfb_packages
  tags:
    - xvfb
